// <auto-generated />
using System;
using MassTransit.Saga.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MassTransit.Saga.EntityFramework.Migrations
{
    [DbContext(typeof(SagaInstanceContext))]
    [Migration("20191128021926_Add-Saga")]
    partial class AddSaga
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MassTransit.Saga.EntityFramework.SagaInstance", b =>
                {
                    b.Property<Guid>("CorrelationId");

                    b.Property<int>("CurrentState");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("ServiceName")
                        .HasMaxLength(40);

                    b.HasKey("CorrelationId");

                    b.ToTable("SagaInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
